# Permalinks
permalink:           pretty

# Setup
title:               Tamara's Blog
tagline:             My first ever blog, loosely about data science
url:                 http://tskootsky.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tamara Skootsky
  url:               https://twitter.com/tskootsky
  email:             tskootsky@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/tskootsky

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
